/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v10.0
processor: MK64FN1M0xxx12
package_id: MK64FN1M0VLL12
mcu_data: ksdk2_0
processor_version: 10.0.0
board: FRDM-K64F
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 0ce4f511-32d0-4c6b-86f5-05bcfa798f20
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * CMP0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CMP0'
- type: 'cmp'
- mode: 'interrupt'
- custom_name_enabled: 'false'
- type_id: 'cmp_306724f57b92dbe1771f1514089d2b18'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CMP0'
- config_sets:
  - fsl_filter:
    - filter_config:
      - filteringOptions: ''
    - quick_selection: 'ContinuousMode'
  - fsl_cmp:
    - main_config:
      - explicitEnableCmp: 'true'
      - hysteresisMode: 'kCMP_HysteresisLevel1'
      - enableHighSpeed: 'false'
      - enableInvertOutput: 'true'
      - useUnfilteredOutput: 'false'
      - enablePinOut: 'true'
    - positiveChannel: 'IN.1'
    - negativeChannel: 'IN.7'
    - enablePassThroughMode: 'true'
  - fsl_dac:
    - enableDAC: 'true'
    - dac_config:
      - referenceVoltageSource: 'DAC_6bit_VIN2'
      - DACValue: '32'
  - interrupt:
    - interrupt_sel: 'kCMP_OutputRisingInterruptEnable kCMP_OutputFallingInterruptEnable'
    - enableDma: 'false'
    - interrupt:
      - IRQn: 'CMP0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - quick_selection: 'QS_IRQ_priority1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* CMP0 main configuration */
const cmp_config_t CMP0_config = {
  .enableCmp = false,
  .hysteresisMode = kCMP_HysteresisLevel1,
  .enableHighSpeed = false,
  .enableInvertOutput = true,
  .useUnfilteredOutput = false,
  .enablePinOut = true,
};
/* Configuration of the DAC sub-module, used in the CMP_SetDACConfig() function */
const cmp_dac_config_t CMP0_dac_config = {
  .referenceVoltageSource = kCMP_VrefSourceVin2,
  .DACValue = 46U
};

static void CMP0_init(void) {
  /* Initialize CMP main sub-module functionality */
  CMP_Init(CMP0_PERIPHERAL, &CMP0_config);
  /* Set up internal DAC sub-module, that can be used as input 7 of the CMP both inputs. */
  CMP_SetDACConfig(CMP0_PERIPHERAL, &CMP0_dac_config);
  /* Initialize CMP main sub-module functionality */
  CMP_SetInputChannels(CMP0_PERIPHERAL, CMP0_POSITIVE_INPUT_NUMBER, CMP0_NEGATIVE_INPUT_NUMBER);
  /* Enables the pass through mode */
  CMP_EnablePassThroughMode(CMP0_PERIPHERAL, true);
  /* Explicitly enables CMP periphery to satisfy glitch limitations. */
  CMP_Enable(CMP0_PERIPHERAL, true);
  /* Select edges which trigger interrupt or DMA transfer if selected */
  CMP_EnableInterrupts(CMP0_PERIPHERAL, kCMP_OutputRisingInterruptEnable);
  /* Enable interrupt CMP0_IRQn request in the NVIC. */
  EnableIRQ(CMP0_IRQN);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  CMP0_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
