/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_cmp.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define CMP0_PERIPHERAL CMP0
/* Definition of positive input source used in CMP_SetInputChannels() function */
#define CMP0_POSITIVE_INPUT_NUMBER 1U
/* Definition of negative input source used in CMP_SetInputChannels() function */
#define CMP0_NEGATIVE_INPUT_NUMBER 7U
/* CMP0 interrupt vector ID (number). */
#define CMP0_IRQN CMP0_IRQn
/* CMP0 interrupt handler identifier. */
#define CMP0_IRQHANDLER CMP0_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const cmp_config_t CMP0_config;
extern const cmp_dac_config_t CMP0_dac_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
